import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import mixins from './mixins';
import css from './assets/css/style.css';
import swipe from '@/assets/js/swiper.js';
import addr from './assets/js/addr.js';
createApp(App).use(store).use(router).mixin(mixins).mount('#app').use(css).use(swipe).use(addr);
window.Kakao.init('61b4bcbd93b6e2039a3f7f7d46cbbe45');
